In [1]:
x = [i for i in range(1, 11)]
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
import numpy as np

In [3]:
x = np.array(x)
print(x * 2)

[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
import pandas as pd

In [6]:
data = {'X': [1,2,3,4,5,6]}

In [9]:
df = pd.DataFrame(data, columns = ['X'])
print(df / 2)

     X
0  0.5
1  1.0
2  1.5
3  2.0
4  2.5
5  3.0


In [10]:
arr1 = np.array([1,2,3,4,5])

In [11]:
arr2 = np.array([6,7,8,9,10])

In [12]:
mat = np.array([arr1, arr2])
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
r1 = [1,2,3]
r2 = [4,5,6]
r3 = [7,8,9]

In [18]:
mat2 = np.asmatrix([r1, r2, r3])
print(mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
mat.shape

(2, 5)

In [28]:
print(np.vstack((mat, arr1, arr2)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [30]:
print(np.column_stack((arr1, arr2, arr2)))

[[ 1  6  6]
 [ 2  7  7]
 [ 3  8  8]
 [ 4  9  9]
 [ 5 10 10]]


In [32]:
data['Y'] = [6,5,4,3,2,1]

In [39]:
df = pd.DataFrame(data)

In [40]:
print(df)

   X  Y
0  1  6
1  2  5
2  3  4
3  4  3
4  5  2
5  6  1


In [41]:
print(list(df))

['X', 'Y']


In [42]:
data = pd.read_csv("Delivery_Time.csv")

In [43]:
print(data)

    Observation  Delivery Time, y  Number of Cases, x1  Distance, x2 (ft)
0             1             16.68                    7                560
1             2             11.50                    3                220
2             3             12.03                    3                340
3             4             14.88                    4                 80
4             5             13.75                    6                150
5             6             18.11                    7                330
6             7              8.00                    2                110
7             8             17.83                    7                210
8             9             79.24                   30               1460
9            10             21.50                    5                605
10           11             40.33                   16                688
11           12             21.00                   10                215
12           13             13.50     

In [54]:
text = pd.read_csv("ex_1_name.txt", header = 0, sep = " ")

In [55]:
print(text)

   Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C


In [56]:
print(text['CA2'])

0    84
1    89
2    86
3    85
4    94
5    84
Name: CA2, dtype: int64


In [58]:
CA3 = [1,2,3,4,5,6]

In [59]:
text['CA3'] = CA3
print(text)

   Subject Gender  CA1  CA2 HW  CA3
0       10      M   80   84  A    1
1        7      M   85   89  A    2
2        4      F   90   86  B    3
3       20      M   82   85  B    4
4       25      F   94   94  A    5
5       14      F   88   84  C    6


In [60]:
iq = pd.read_csv('ex_1_IQ.txt', header = 0, sep = " ")

In [63]:
print(iq["IQ"])

0    106
1    112
2    119
3    102
4    125
5    101
Name: IQ, dtype: int64


In [69]:
text = text.drop(['CA3'], axis = 1)
print(text)

   Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C


In [70]:
text

Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C

In [71]:
frames = [text, iq['IQ']]

In [77]:
result = pd.concat(frames, axis = 1)

In [78]:
print(result)

   Subject Gender  CA1  CA2 HW   IQ
0       10      M   80   84  A  106
1        7      M   85   89  A  112
2        4      F   90   86  B  119
3       20      M   82   85  B  102
4       25      F   94   94  A  125
5       14      F   88   84  C  101


In [80]:
import statistics

In [88]:
statistics.variance(x)

9

In [89]:
text

Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C

In [95]:
CA1 = text['CA1']

pandas.core.series.Series

In [92]:
f = open('CA1.csv', 'w')

In [93]:
for i in CA1:
    f.write(str(i) + '\n')
f.close()

In [94]:
CA1

0    80
1    85
2    90
3    82
4    94
5    88
Name: CA1, dtype: int64

In [96]:
f = open('test.csv', 'w')

In [97]:
for i in text:
    f.write(str(i) + '\n')
f.close()

In [105]:
np.savetxt('test.txt', text, fmt='%s')

In [104]:
text

Subject Gender  CA1  CA2 HW
0       10      M   80   84  A
1        7      M   85   89  A
2        4      F   90   86  B
3       20      M   82   85  B
4       25      F   94   94  A
5       14      F   88   84  C

In [110]:
text.to_csv('test.csv', header = None, index=None, sep=',', mode='a')